#pragma once

#define PORT_STRING_SIZE 6
#define SOCKET_WORD_DELIMITER ' '
#define SOCKET_COMMAND_DELIMITER_0 '\r'
#define SOCKET_COMMAND_DELIMITER_1 '\n'
#define SERIALIZER_MAX_PAYLOAD_SIZE 1400
#define FILE_SHARED_FOLDER "shared/"
#define UPLOAD_DOWNLOAD_SIZE_TYPE uint16_t
#define COMMUNICATION_PORT 27777
#define COMMUNICATION_TIMEOUT_SECONDS 30
